# GAE app settings
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    script: src.main.app
    login: admin
    secure: always

  - url: /slack/commands
    script: src.main.app
    secure: always

  - url: /slack/event
    script: src.main.app
    secure: always

libraries:
- name: ssl
  version: "2.7.11"

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  
